### ISSUE TITLE
Project V1 Review

### ISSUE THREAD

**Issue by jhoffman12** [annieliu2/Project#3]
Content:
1. Maybe provide a brief description of what to expect on the website on the homepage
2. Maybe under each recipe provide a snack that it would be a good pair with, for example cookies with warm milk or cheesecake with coffee
Technical:
1. Check the link to your bread page because nothing comes up when you click on it
2. On the cakes page the title still says cookies and there is a > sign that needs to be removed

**Comment by annieliu2** [comment]
Thank you for your advice, Jamie! I would take your suggestions into account for the second part of the project. I like your idea of pairing each dessert with a drink.
