### ISSUE TITLE
Project V1 Review 

### ISSUE THREAD

**Issue by mmadison1** [annieliu2/Project#4]
I love the picture on your home page but I would recommend to make it a bit smaller and add a description letting your audience know what your website will be about. Also, I loved how you used a form in each of the sections, I would just recommend to line up your text so it looks cleaner! The only technical issue I had was that the bread and brownie tabs would not open.

**Comment by annieliu2** [comment]
Thank you for your advice Madison! I agree with your suggestions and I will put them in place for the second version. Also, the bread and brownie tabs have not been completed yet so that's probably why they didn't open.
