### ISSUE TITLE
Proj v1 peer review

### ISSUE THREAD

**Issue by elitvak1** [annieliu2/Project#5]
Great use of white space. I like the contrast that the link bar at the top creates with the white background. The photo color palette works really well with the minimalist design. I suggest a more sophisticated font for both titles and links. I also recommend putting all links in one row equally spaced apart. Great use of tables here, but I think it would be promising to increase the width of all the recipe tables so the info reads more easily.

**Comment by annieliu2** [comment]
Thanks for the advice! I was also thinking of changing the font for the headers but haven't found the right one yet.
